config/routes.rb
Rails.application.routes.draw do
  resources :employees do
    resources :contracts
  end
  root 'static#index'
end

app/models/employee.rb
class Employee < Sequel::Model
  plugin :bitemporal, version_class: EmployeeVersion

  one_to_many :contracts

  dataset_module do
    def by_name(name = nil)
      return eager_graph(:current_version).all unless name

      # Note the | operator for OR (https://github.com/jeremyevans/sequel/blob/master/doc/querying.rdoc#label-SQL-3A-3AExpression)
      eager_graph(:current_version).where(
        Sequel.like(Sequel.function(:lower, :first_name), "%#{name.downcase}%") |
        Sequel.like(Sequel.function(:lower, :last_name), "%#{name.downcase}%")
      ).all
    end

    # Avoid N+1
    def eager_contracts
      eager_graph(:current_version, contracts: :current_version)
    end

    # all employees with current contract fields
    def join_contracts
      association_left_join(:current_version, contracts: :current_version)
    end

    # dataset for employees with a current contract fields
    def with_current_contract
      today = Time.zone.today
      with_contracts.where(Sequel.lit("start_date <= ? AND end_date >= ?", today, today))
    end

    # query by contract's legal
    def by_legal(legal)
      join_contracts.where(Sequel.like(Sequel.function(:lower, :legal), "%#{legal.downcase}%"))
    end
  end
end

# Employee.association_left_join(:current_version, contracts: :current_version)
# SELECT * FROM `employees`
# LEFT JOIN `employee_versions` AS 'employee_current_version'
#   ON (
#     (`employee_current_version`.`master_id` = `employees`.`id`)
#     AND (`employee_current_version`.`created_at` <= '2022-03-02 20:23:29.981147')
#     AND (
#       (`employee_current_version`.`expired_at` IS NULL)
#       OR (`employee_current_version`.`expired_at` > '2022-03-02 20:23:29.981482')
#     )
#     AND (`employee_current_version`.`valid_from` <= '2022-03-02 20:23:29.981696')
#     AND (`employee_current_version`.`valid_to` > '2022-03-02 20:23:29.981869')
#   )
# LEFT JOIN `contracts`
#   ON (`contracts`.`employee_id` = `employees`.`id`)
# LEFT JOIN `contract_versions` AS 'contract_current_version'
#   ON (
#     (`contract_current_version`.`master_id` = `contracts`.`id`)
#     AND (`contract_current_version`.`created_at` <= '2022-03-02 20:23:29.982078')
#     AND (
#       (`contract_current_version`.`expired_at` IS NULL)
#       OR (`contract_current_version`.`expired_at` > '2022-03-02 20:23:29.982259')
#     )
#     AND (`contract_current_version`.`valid_from` <= '2022-03-02 20:23:29.982431')
#     AND (`contract_current_version`.`valid_to` > '2022-03-02 20:23:29.982598')
#   )

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  def index
    @employees = Employee.by_name(params[:name])
  end

  # GET /employees/1
  def show
    params[:validity] ||= Time.zone.today

    Sequel::Plugins::Bitemporal.at(params[:validity]) do
      @employee.current_version(reload: true)
    end

    @versions = @employee.versions_dataset.order(:id).all
    @contracts = @employee.contracts
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  def create
    @employee = Employee.new

    if @employee.update_attributes(employee_params)
      redirect_to employee_url(@employee.id), notice: "Employee was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /employees/1
  def update
    params[:validity] ||= Time.zone.today

    Sequel::Plugins::Bitemporal.at(params[:validity]) do
      @employee.update_attributes(employee_params)
      @employee.current_version(reload: true)
    end

    if @employee.errors.empty?
      redirect_to employee_url(@employee.id), notice: "Employee was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /employees/1
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find(id: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :birthday, :address)
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_contracts.html.erb
<div class="card shadow-sm mt-4">
  <div class="card-header">
    <h4 class="mb-0">List of contracts</h4>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-striped table-hover table-bordered text-center">
        <thead>
          <tr>
            <th>Start date</th>
            <th>End date</th>
            <th>Legal</th>
            <th colspan="3">Action</th>
          </tr>
        </thead>

        <tbody>
          <% @contracts.each do |contract| %>
            <tr>
              <td><%= contract.start_date %></td>
              <td><%= contract.end_date %></td>
              <td><%= contract.legal %></td>
              <td><%= link_to 'Show', employee_contract_path(@employee.id, contract.id) %></td>
              <td><%= link_to 'Edit', edit_employee_contract_path(@employee.id, contract.id) %></td>
              <td><%= link_to 'Destroy', employee_contract_path(@employee.id, contract.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/employees/_filter.html.erb
<div class="card shadow-sm">
  <div class="card-body">
    <%= form_with url: employee_path(@employee.id), method: :get, class: 'search-form' do |f| %>
      <div class="row mb-2">
        <%= f.label :validity, 'Validity date', class: 'col-sm-2 col-form-label text-end' %>
        <div class="col-sm-4">
          <%= f.date_field :validity, class: 'form-control', value: params[:validity] %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/employees/_form.html.erb
<div class="card shadow-sm mt-4">
  <div class="card-header">
    <h4 class="mb-0">Personal data</h4>
  </div>
  <div class="card-body">
    <%= form_for(:employee, form_option_builder(employee)) do |f| %>

      <% if employee.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h2><%= pluralize(employee.errors.count, "error") %> prohibited this contract from being saved:</h2>

          <ul class="mb-0">
            <% employee.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= hidden_field_tag :validity, params[:validity] %>

      <div class="row mb-2">
        <%= f.label :first_name, class: 'col-sm-2 col-form-label text-end' %>
        <div class="col-sm-10">
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>
      </div>

      <div class="row mb-2">
        <%= f.label :last_name, class: 'col-sm-2 col-form-label text-end' %>
        <div class="col-sm-10">
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
      </div>

      <div class="row mb-2">
        <%= f.label :birthday, class: 'col-sm-2 col-form-label text-end' %>
        <div class="col-sm-10">
          <%= f.date_field :birthday, class: 'form-control' %>
        </div>
      </div>

      <div class="row mb-2">
        <%= f.label :address, class: 'col-sm-2 col-form-label text-end' %>
        <div class="col-sm-10">
          <%= f.text_area :address, class: 'form-control' %>
        </div>
      </div>

      <div class="d-grid mt-4">
        <%= f.submit 'Submit', class: 'btn btn-lg btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/employees/_search.html.erb
<div class="card shadow-sm">
  <div class="card-body">
    <%= form_with url: employees_path, method: :get, class: 'search-form' do |f| %>
      <div class="row mb-2">
        <%= f.label :name, 'Name contains', class: 'col-sm-2 col-form-label text-end' %>
        <div class="col-sm-10">
          <%= f.text_field :name, class: 'form-control', value: params[:name] %>
        </div>
      </div>

      <%#= f.submit 'Filter', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/employees/_versions.html.erb
<div class="card shadow-sm my-4">
  <div class="card-header">
    <h4 class="mb-0">List of versions</h4>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-striped table-hover table-bordered text-center">
        <thead>
          <tr>
            <th>ID</th>
            <th>Master Id</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Birthday</th>
            <th>Address</th>
            <th>Valid From</th>
            <th>Valid To</th>
            <th>Created At</th>
            <th>Expired At</th>
          </tr>
        </thead>

        <tbody>
          <% @versions.each do |version| %>
            <tr>
              <td><%= version.id %></td>
              <td><%= version.master_id %></td>
              <td><%= version.first_name %></td>
              <td><%= version.last_name %></td>
              <td><%= version.birthday %></td>
              <td><%= version.address %></td>
              <td><%= version.valid_from %></td>
              <td><%= version.valid_to %></td>
              <td><%= version.created_at %></td>
              <td><%= version.expired_at %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/employees/edit.html.erb
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item active">Employees <span class="badge bg-warning">UPDATE</span></li>
  <%= back_to employees_path %>
<% end %>

<% content_for :functions do %>
  <%= link_to 'Show', employee_path(@employee.id), class: 'btn btn-info text-white' %>
<% end %>

<%= render 'form', employee: @employee %>

app/views/employees/index.html.erb
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item active">Employees <span class="badge bg-primary">List</span></li>
<% end %>

<% content_for :functions do %>
  <%= link_to 'New Employee', new_employee_path, class: 'btn btn-primary' %>
<% end %>

<%# Search Form %>
<%= render 'employees/search' %>

<p id="notice"><%= notice %></p>

<div class="card shadow-sm">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-striped table-hover table-bordered text-center">
        <thead>
          <tr>
            <th>First name</th>
            <th>Last name</th>
            <th>Birthday</th>
            <th>Address</th>
            <th colspan="3">Action</th>
          </tr>
        </thead>

        <tbody>
          <% @employees.each do |employee| %>
            <tr>
              <td><%= employee.first_name %></td>
              <td><%= employee.last_name %></td>
              <td><%= employee.birthday %></td>
              <td><%= employee.address %></td>
              <td><%= link_to 'Show', employee_path(employee.id) %></td>
              <td><%= link_to 'Edit', edit_employee_path(employee.id) %></td>
              <td><%= link_to 'Destroy', employee_path(employee.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item active">Employees <span class="badge bg-info">ADD</span></li>
  <%= back_to employees_path %>
<% end %>

<%= render 'form', employee: @employee %>

app/views/employees/show.html.erb
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item active">Employees <span class="badge bg-success">DETAIL</span></li>
  <%= back_to employees_path %>
<% end %>

<% content_for :functions do %>
  <%= link_to 'New Contract', new_employee_contract_path(employee_id: @employee.id), class: 'btn btn-primary' %>
<% end %>

<p id="notice"><%= notice %></p>

<%= render 'employees/filter' %>
<%= render 'employees/form', employee: @employee %>
<%= render 'employees/contracts' if @contracts %>
<%= render 'employees/versions' if @versions %>